CREATE OR REPLACE PROCEDURE BASKET_ADD_SP (
    p_product_id   IN NUMBER,      -- Product ID
    p_basket_id    IN NUMBER,      -- Basket ID
    p_price        IN NUMBER,      -- Price of the item
    p_quantity     IN NUMBER,      -- Quantity of the item
    p_size_code    IN NUMBER,      -- Size code (1 or 2)
    p_form_code    IN NUMBER       -- Form code (3 or 4)
) IS
BEGIN
    -- Insert a new item into the BB_BASKETITEM table
    INSERT INTO BB_BASKETITEM (
        IDBASKETITEM,    -- Primary key, generated by the sequence
        IDBASKET,        -- Basket ID
        IDPRODUCT,       -- Product ID
        PRICE,           -- Price
        QUANTITY,        -- Quantity
        OPTION1,       -- Size code
        OPTION2       -- Form code
               
    )
    VALUES (
        BB_IDBASKETITEM_SEQ.NEXTVAL,  -- Get the next value from the sequence for the primary key
        p_basket_id,                  -- Basket ID passed as parameter
        p_product_id,                 -- Product ID passed as parameter
        p_price,                      -- Price passed as parameter
        p_quantity,                   -- Quantity passed as parameter
        p_size_code,                  -- Size code passed as parameter
        p_form_code                 -- Form code passed as parameter
        
    );

    -- Commit the transaction if not using autocommit
    COMMIT;

    -- Optionally, you could output a confirmation message for debugging or logging
    DBMS_OUTPUT.PUT_LINE('Item added to basket ' || p_basket_id || ' for product ' || p_product_id);

EXCEPTION
    WHEN OTHERS THEN
        -- Rollback if any error occurs
        ROLLBACK;
        -- Output the error message for debugging
        DBMS_OUTPUT.PUT_LINE('Error occurred while adding item to basket: ' || SQLERRM);
END BASKET_ADD_SP;
/

--Execution Procedure
BEGIN
    BASKET_ADD_SP(
        p_product_id => 8,
        p_basket_id  => 14,
        p_price      => 10.80,
        p_quantity   => 1,
        p_size_code  => 2,
        p_form_code  => 4
    );
END;
/
